name: example-env
channels:
  - conda-forge
dependencies:
  - datacube>=1.8
  - geocube>=0.0.16
  - geopandas>=0.3
  - numpy>=1.20
  - pandas>=1.0
  - pyproj>=3.0
  - pytz
  - rasterio>=1.2
  - rioxarray>=0.4
  - scipy>=1.3.0
  - xarray>=0.1
